### ISSUE TITLE
Connection to the Odoo server

### ISSUE THREAD

**Issue by excellencemichel** [mustafal/Odoo-JsonRpc-with-Flutter#5]
I am try to connect to the Odoo instance (Odoo server) but it isn't work.
Here is the error : 
`Error connecting to the service protocol: failed to connect to http://127.0.0.1`

**Comment by mustafal** [comment]
do you have change the URL in config.dart?

**Comment by alpriansyah** [comment]
> do you have change the URL in config.dart?

how i can get uid or current user id?

**Comment by mustafal** [comment]
`currentUser.value.uid`
